
#define EE_HANDS
// #define MASTER_LEFT

// #define MATRIX_COL_PINS { GP7, GP6, GP5, GP4, GP3, GP2, GP8, GP9 }
// #define MATRIX_ROW_PINS { GP20, GP23, GP21 }

// #define MATRIX_COL_PINS_RIGHT { GP20, GP22, GP26, GP27, GP28, GP29, GP23, GP21 }
// #define MATRIX_ROW_PINS_RIGHT { GP7, GP8, GP9 }

// #define DIODE_DIRECTION COL2ROW
#define TAPPING_TERM 300
#define QUICK_TAP_TERM 50

#define SERIAL_USART_FULL_DUPLEX // Enable full duplex operation mode.
#define SERIAL_USART_TX_PIN GP0  // USART TX pin
#define SERIAL_USART_RX_PIN GP1  // USART RX pin

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define SPLIT_LED_STATE_ENABLE
